from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Category", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80, unique=True))]),
        migrations.CreateModel(name="Profile", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("photo", models.ImageField(blank=True, null=True, upload_to="profiles/")), ("bio", models.TextField(blank=True)), ("district", models.CharField(blank=True, max_length=60)), ("verified", models.BooleanField(default=False, help_text="Admin controlled. Turn on only after verification.")), ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="SiteSettings", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("hero_title", models.CharField(default="Naatilevide", max_length=180)), ("hero_text", models.TextField(default="Naattinte kathakal, sthalangal, aalkkaar — ellam oru idath.")), ("hero_image", models.ImageField(blank=True, null=True, upload_to="site/")), ("about_title", models.CharField(default="Our Kerala", max_length=180)), ("about_text", models.TextField(blank=True)), ("favicon", models.ImageField(blank=True, null=True, upload_to="site/")), ("adsense_enabled", models.BooleanField(default=False)), ("adsense_client", models.CharField(blank=True, max_length=120))]),
        migrations.CreateModel(name="Advertisement", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=180)), ("shop_name", models.CharField(max_length=160)), ("media_type", models.CharField(choices=[("IMAGE", "Image"), ("VIDEO", "Video")], default="IMAGE", max_length=10)), ("image", models.ImageField(blank=True, null=True, upload_to="ads/images/")), ("video", models.FileField(blank=True, null=True, upload_to="ads/videos/")), ("target_url", models.URLField(blank=True)), ("enabled", models.BooleanField(default=False)), ("start_at", models.DateTimeField(blank=True, null=True)), ("end_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="Follow", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("follower", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="following", to=settings.AUTH_USER_MODEL)), ("following", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="followers", to=settings.AUTH_USER_MODEL))], options={"constraints": [models.UniqueConstraint(fields=("follower", "following"), name="unique_user_follow")]}),
        migrations.CreateModel(name="Blog", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(choices=[("PENDING", "Pending verification"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=10)), ("rejection_reason", models.TextField(blank=True)), ("submitted_at", models.DateTimeField(auto_now_add=True)), ("reviewed_at", models.DateTimeField(blank=True, null=True)), ("title", models.CharField(max_length=180)), ("content", models.TextField()), ("cover", models.ImageField(blank=True, null=True, upload_to="blogs/")), ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="blogs", to=settings.AUTH_USER_MODEL)), ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.category"))], options={"ordering": ["-submitted_at"]}),
        migrations.CreateModel(name="Place", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(choices=[("PENDING", "Pending verification"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=10)), ("rejection_reason", models.TextField(blank=True)), ("submitted_at", models.DateTimeField(auto_now_add=True)), ("reviewed_at", models.DateTimeField(blank=True, null=True)), ("name", models.CharField(max_length=160)), ("district", models.CharField(max_length=60)), ("location", models.CharField(max_length=220)), ("description", models.TextField()), ("image", models.ImageField(blank=True, null=True, upload_to="places/")), ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)), ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)), ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="places", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-submitted_at"]}),
        migrations.CreateModel(name="Event", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(choices=[("PENDING", "Pending verification"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=10)), ("rejection_reason", models.TextField(blank=True)), ("submitted_at", models.DateTimeField(auto_now_add=True)), ("reviewed_at", models.DateTimeField(blank=True, null=True)), ("title", models.CharField(max_length=180)), ("location", models.CharField(max_length=220)), ("event_date", models.DateTimeField()), ("description", models.TextField()), ("image", models.ImageField(blank=True, null=True, upload_to="events/")), ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to=settings.AUTH_USER_MODEL))], options={"ordering": ["event_date"]}),
        migrations.CreateModel(name="GalleryItem", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(choices=[("PENDING", "Pending verification"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=10)), ("rejection_reason", models.TextField(blank=True)), ("submitted_at", models.DateTimeField(auto_now_add=True)), ("reviewed_at", models.DateTimeField(blank=True, null=True)), ("image", models.ImageField(upload_to="gallery/")), ("caption", models.CharField(blank=True, max_length=220)), ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gallery", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Notification", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("text", models.CharField(max_length=255)), ("read", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="Report", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("target_type", models.CharField(choices=[("BLOG", "Blog"), ("PLACE", "Place"), ("EVENT", "Event"), ("USER", "User")], max_length=10)), ("target_id", models.PositiveIntegerField()), ("reason", models.CharField(max_length=180)), ("details", models.TextField(blank=True)), ("resolved", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("reporter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reports", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
    ]
